version: '3.1'

services:

  mysql:
    container_name: mysql
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 15243
      MYSQL_USER: priyam
      MYSQL_PASSWORD: 15243
      MYSQL_DATABASE: spring-batch-poc
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 9022:80
    volumes:
      - /sessions
    external_links:
      - mysql:db
